version: "3"

services:

  node1:
    image: fabricedupre/mariadb-galeracluster:latest 
    hostname: node1 
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=test
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=testpass
    volumes:
      - Volumenode1VarLibMysql:/var/lib/mysql
      - Volumenode1VarLogMysql:/var/log/mysql
      - Volumenode1UsrLibGalera:/usr/lib/galera
      - VolumeSVGMysql:/mnt
    networks:
      - mariadb-network
    command: --max_allowed_packet=536870912 --character-set-server=utf8 --collation-server=utf8_unicode_ci --query_cache_size=0 --query_cache_type=OFF --log_bin=/var/log/mysql/mariadb-bin --wsrep_on=ON --wsrep_provider=/usr/lib/galera/libgalera_smm.so --wsrep_cluster_address=gcomm:// --binlog_format=row --default_storage_engine=InnoDB --innodb_autoinc_lock_mode=2 --bind-address=0.0.0.0 --wsrep_slave_threads=1 --innodb_flush_log_at_trx_commit=2
    healthcheck:
      test: mysqladmin ping -uroot -pk3O2Iyd89cnqV0IQx7qV

  node2:
    image: fabricedupre/mariadb-galeracluster:latest 
    hostname: node2
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=test
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=testpass
    volumes:
      - Volumenode2VarLibMysql:/var/lib/mysql
      - Volumenode2VarLogMysql:/var/log/mysql
      - Volumenode2UsrLibGalera:/usr/lib/galera
    depends_on:
      - node1 
    networks:
      - mariadb-network
    command: --max_allowed_packet=536870912 --character-set-server=utf8 --collation-server=utf8_unicode_ci --query_cache_size=0 --query_cache_type=OFF --log_bin=/var/log/mysql/mariadb-bin --wsrep_on=ON --wsrep_provider=/usr/lib/galera/libgalera_smm.so --wsrep_cluster_address=gcomm://GALERACLUSTER_node1,GALERACLUSTER_node2 --binlog_format=row --default_storage_engine=InnoDB --innodb_autoinc_lock_mode=2 --bind-address=0.0.0.0 --wsrep_slave_threads=1 --innodb_flush_log_at_trx_commit=2
    healthcheck:
      test: mysqladmin ping -uroot -prootpass

  node3:
    image: fabricedupre/mariadb-galeracluster:latest 
    hostname: node3
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasss
      - MYSQL_DATABASE=test
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=testpass
    volumes:
      - Volumenode3VarLibMysql:/var/lib/mysql
      - Volumenode3VarLogMysql:/var/log/mysql
      - Volumenode3UsrLibGalera:/usr/lib/galera
    networks:
      - mariadb-network
    depends_on:
      - node2 
    command: --max_allowed_packet=536870912 --character-set-server=utf8 --collation-server=utf8_unicode_ci --query_cache_size=0 --query_cache_type=OFF --log_bin=/var/log/mysql/mariadb-bin --wsrep_on=ON --wsrep_provider=/usr/lib/galera/libgalera_smm.so --wsrep_cluster_address=gcomm://GALERACLUSTER_node1,GALERACLUSTER_node2,GALERACLUSTER_node3 --binlog_format=row --default_storage_engine=InnoDB --innodb_autoinc_lock_mode=2 --bind-address=0.0.0.0 --wsrep_slave_threads=1 --innodb_flush_log_at_trx_commit=2
    healthcheck:
      test: mysqladmin ping -uroot -prootpass

  lb:
    image: nginx
    hostname: lb
    volumes:
      - $PWD/nginx_GALERACLUSTER.conf:/etc/nginx/nginx.conf
    networks:
      - mariadb-network
    depends_on:
      - node3
    ports:
      - 33064:3306

networks:
  mariadb-network:
    driver: overlay
    external: true
volumes:
  Volumenode1VarLibMysql:
    driver: global 
  Volumenode1VarLogMysql:
    driver: global 
  Volumenode1UsrLibGalera:
    driver: global
  Volumenode2VarLibMysql:
    driver: global
  Volumenode2VarLogMysql:
    driver: global
  Volumenode2UsrLibGalera:
    driver: global
  Volumenode3VarLibMysql:
    driver: global
  Volumenode3VarLogMysql:
    driver: global
  Volumenode3UsrLibGalera:
    driver: global
  VolumeSVGMysql:
    driver: global
