version: "3"

services:

  db:
    image: fabricedupre/mariadb-ubuntu:latest
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=test
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=testpass
    volumes:
      - VolumeDBVarLibmysql:/var/lib/mysql
      - VolumeDBVarLogmysql:/var/log/mysq
      - VolumeSVGMysql:/mnt 
    ports:
      - 33062:3306
    command: --max_allowed_packet=536870912 --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - mariadb-network
    healthcheck:
      test: mysqladmin ping -uroot -prootpass

networks:
  mariadb-network:
    driver: overlay
    external: true
volumes:
  VolumeDBVarLibmysql:
    driver: local
  VolumeDBVarLogmysql:
    driver: local
  VolumeSVGMysql:
    driver: local
