version: "3"

services:

  db:
    image: dtr-v-rr.docker.opteama.net:443/stelia/mariadb:latest
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=opteama
      - MYSQL_USER=opteama_user
      - MYSQL_PASSWORD=opteamapass
    volumes:
      - VolumeDBVarLibmysql:/var/lib/mysql
      - VolumeDBVarLogmysql:/var/log/mysq
      - VolumeSVGMysql:/mnt 
    ports:
      - <PORT_MARIA>:3306
    command: --max_allowed_packet=536870912 --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - mariadb-network
    healthcheck:
      test: mysqladmin ping -uroot -prootpass

networks:
  mariadb-network:
    driver: overlay
    external: true
volumes:
  VolumeDBVarLibmysql:
    driver: netapp
    driver_opts:
      size: 100g
  VolumeDBVarLogmysql:
    driver: netapp
    driver_opts:
      size: 10g
  VolumeSVGMysql:
    driver: netapp
    driver_opts:
      size: 100g
